name: stoquer
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  cloud_firestore: ^4.17.3
  firebase_storage: ^11.7.5

  # State Management
  provider: ^6.1.5

  # Features
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.0.1
  image_picker: ^1.1.2
  fl_chart: ^1.0.0

  # PDF & Printing
  printing: ^5.12.0
  pdf: ^3.10.8

  # Utilities
  logger: ^2.6.0
  uuid: ^4.5.1
  intl: ^0.20.2

  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  dart_code_metrics: ^4.15.0   # â† Aqui! adicione o pacote

flutter:
  uses-material-design: true
